services:
  - type: web
    name: halls-backend
    env: python
    plan: free
    runtime: python3
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: halls-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
      - key: JWT_SECRET
      - key: JWT_ALGORITHM
      - key: RAZORPAY_KEY_ID
      - key: RAZORPAY_KEY_SECRET

databases:
  - name: halls-db
    plan: free
